# Generated by Django 5.2.15 on 2026-06-21 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('diets', '0004_ai_diet_plans_and_snapshots'),
        ('workouts', '0005_workoutlogset_and_log_compatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_saved_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='diets.savedmeal'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_saved_meal_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_workout_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='workouts.workoutroutine'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_workout_routine_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SharedPostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_type', models.CharField(choices=[('saved_meal', 'Saved Meal'), ('workout_routine', 'Workout Routine')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_saves', to='community.post')),
                ('saved_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_post_save_records', to='diets.savedmeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post_saves', to=settings.AUTH_USER_MODEL)),
                ('workout_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_post_save_records', to='workouts.workoutroutine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'post', 'save_type'), name='unique_user_post_shared_save_type')],
            },
        ),
    ]
